---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: gbarbieru/xenial

suites:
  - name: default
    run_list:
      - recipe[python_pip_django::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: install_pip
    run_list:
      - recipe[python_pip_django::install_pip]
  - name: install_virtualenv
    run_list:
      - recipe[python_pip_django::install_virtualenv]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
